# Generated by Django 5.1.2 on 2025-01-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tblfooter_tblslides_tblsocialmedia_tblsubtopmenu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblClients',
        ),
        migrations.RemoveField(
            model_name='tblsubfooter',
            name='footerID',
        ),
        migrations.RemoveField(
            model_name='tblproductdetail',
            name='productID',
        ),
        migrations.DeleteModel(
            name='tblSlides',
        ),
        migrations.RemoveField(
            model_name='tblsub2topmenu',
            name='subTopMenuID',
        ),
        migrations.RemoveField(
            model_name='tblsubtopmenu',
            name='TopMenuID',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CategoryImage',
            new_name='categoryImage',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='categoryName',
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='productImage',
            field=models.ImageField(upload_to='Productimages/'),
        ),
        migrations.AlterField(
            model_name='tblsocialmedia',
            name='socialMediaImage',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.DeleteModel(
            name='tblFooter',
        ),
        migrations.DeleteModel(
            name='tblSubFooter',
        ),
        migrations.DeleteModel(
            name='tblProductDetail',
        ),
        migrations.DeleteModel(
            name='tblSub2TopMenu',
        ),
        migrations.DeleteModel(
            name='tblSubTopMenu',
        ),
        migrations.DeleteModel(
            name='tblTopMenu',
        ),
    ]
