# Generated by Django 5.1.2 on 2025-01-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_tblclients_remove_tblsubfooter_footerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblTopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topMenuName', models.CharField(max_length=200, null=True)),
                ('topMenuImage', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='tblSubTopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTopMenuName', models.CharField(max_length=200, null=True)),
                ('subTopMenuImage', models.ImageField(upload_to='SubTopMenu')),
                ('TopMenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tbltopmenu')),
            ],
        ),
    ]
