# Generated by Django 5.1.2 on 2025-01-24 01:17

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tbltopmenu_tblsubtopmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTypeName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogName', models.CharField(max_length=200, null=True)),
                ('BlogDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('BlogDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('BlogTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tbltopmenu')),
            ],
        ),
    ]
