# Generated by Django 5.1.2 on 2025-01-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tblblogtype_tblblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproducts',
            name='categoryID',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='tblProducts',
        ),
    ]
