# Generated by Django 5.1.2 on 2025-01-24 15:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_category_tblproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDetailName', models.CharField(max_length=200, null=True)),
                ('productDetailDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('productSize', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('productColor', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblproducts')),
            ],
        ),
    ]
