# Generated by Django 5.1.2 on 2025-01-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_pricein_tblproducts_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblproducts',
            old_name='quantity',
            new_name='product_ratting',
        ),
    ]
