# Generated by Django 5.1.2 on 2025-01-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_quantity_tblproducts_product_ratting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproducts',
            name='ProductID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tbltopmenu'),
        ),
    ]
