# Generated by Django 5.1.2 on 2025-01-26 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_tblproducts_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproducts',
            name='ProductID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tbltopmenu'),
        ),
    ]
