# Generated by Django 5.1.2 on 2025-01-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_tblproducts_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproducts',
            name='ProductID',
        ),
    ]
