# Generated by Django 5.1.2 on 2025-01-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_tblproducts_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblblog',
            name='BlogTypeID',
        ),
        migrations.DeleteModel(
            name='TblBlogType',
        ),
        migrations.DeleteModel(
            name='TblBlog',
        ),
    ]
