# Generated by Django 5.1.2 on 2025-01-27 17:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_tblproducts_instock_tblproducts_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideName', models.CharField(max_length=200, null=True)),
                ('slideImage', models.ImageField(null=True, upload_to='images/')),
                ('slideDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('active', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
