# Generated by Django 5.1.2 on 2025-01-27 17:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_tblslides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblslides',
            name='active',
        ),
        migrations.AddField(
            model_name='tblslides',
            name='smallslideDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
