# Generated by Django 5.1.2 on 2025-01-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_tblslides_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblslides',
            name='slideDescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tblslides',
            name='smallslideDescription',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
