# Generated by Django 5.1.2 on 2025-01-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_tblslides_slidedescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logoImg')),
                ('SpanContact', models.CharField(max_length=200, null=True)),
                ('Contact', models.CharField(max_length=200, null=True)),
                ('SpanLocation', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
