# Generated by Django 5.1.2 on 2025-01-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_tblfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblfooter',
            name='footerName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
