# Generated by Django 5.1.2 on 2025-02-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_tblproducts_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblblog',
            old_name='BlogDate',
            new_name='BlogURL',
        ),
        migrations.RemoveField(
            model_name='tblblog',
            name='BlogTypeID',
        ),
    ]
