# Generated by Django 5.1.2 on 2025-02-06 02:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_delete_tblblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogName', models.CharField(max_length=200, null=True)),
                ('BlogDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('BlogDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('BlogURL', models.CharField(max_length=200, null=True)),
                ('BlogImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
