# Generated by Django 5.1.2 on 2025-02-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_tblblog_blogdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblblog',
            name='BlogDescription',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
